### ISSUE TITLE
Facing error while installing pango

### ISSUE THREAD

**Issue by sushantag9** [ihdia/sanskrit-ocr#3]
What is the python version used to install pango and generate the synthetic data. In the file "get_random_lines.py" in the line 
`pangocairo_context = pangocairo.CairoContext(context)`

**Comment by captainCod3** [comment]
Hi @sushantag9 , 

I used python 2.7.17 to work with Pango and Cairo. I have some issues while installing Pango Cairo in python3

**Comment by sushantag9** [comment]
Ok thanks
