### ISSUE TITLE
How to install this module

### ISSUE THREAD

**Issue by Aditya-R-K** [ihdia/sanskrit-ocr#32]
Please let me know how to install this module in python & use it for the images

**Comment by khadiravana-belagavi** [comment]
which module are you referring to? The sanskrit-ocr module? Kindly refer to the [readme](https://github.com/ihdia/sanskrit-ocr/blob/main/README.md#indicocr-v2) provided .

**Comment by khadiravana-belagavi** [comment]
Closing this issue -- since there is no more discussion for quite some time.
