### ISSUE TITLE
Tensorflow Serve Error 

### ISSUE THREAD

**Issue by sushantag9** [ihdia/sanskrit-ocr#4]
external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at ctc_decoder_ops.cc:288 : Failed precondition: sequence_length(0) <= 128

I am getting this error

**Comment by captainCod3** [comment]
Hey, can you please describe how did you get this error?

**Comment by sushantag9** [comment]
I tried to deploy the model with tf serving. Then when I decoded the part of the model it's after the shadownet model when the error is there.

**Comment by captainCod3** [comment]
Have you changed the CHARMAP that was defined in data_gen.py file?

**Comment by khadiravana-belagavi** [comment]
Closing this issue -- since there is no more discussion for quite some time.
